name: Version and Release Workflow
on:
  pull_request:
    types:
      - closed
permissions:
  contents: write
  pull-requests: write

jobs:
  version_release_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Use your composite action
      - name: Release on PR merge
        uses: dragolea/composite-actions@main # Replace with the branch or tag of your composite action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
